keywords = {
    "fun": "FUN",
    "class": "CLASS",
    "val": "VAL",
    "var": "VAR",
    "if": "IF",
    "else": "ELSE",
    "for": "FOR",
    "while": "WHILE",
    "when": "WHEN",
    "as": "AS",
    "is": "IS",
    "in": "IN",
    "continue": "CONTINUE",
    "break": "BREAK",
    "return": "RETURN",
}
